### ISSUE TITLE
Wrong references in change model

### ISSUE THREAD

**Issue by TheoLeCalvar** [TransformationToolContest/ttc2019-live#4]
Change models refer to the original DocBook models but the URIs are wrong.

For instance, in [random10-single-1](https://github.com/TransformationToolContest/ttc2019-live/blob/master/models/random10/random10-single-1/applied.changes#L4), the refered docbook is `../random10.docbook` but the file is located one folder above, the correct URI should be `../../random10.docbook`.

**Comment by ValentinBesnard** [comment]
Hi,

I think there is also another kind of issue in change model. References to model elements seem incorrect in addition to incorrect references to URI.

In the same model (random10-single-1), I think the `affectedElement` is incorrect. I guess the `affectedElement` should be `se2` while `09a6ddf5-620b-433f-a14e-0e72648d4db7` should be the id of the `deletedElement' (omitted here).

Regards

Valentin

**Comment by agarciadom** [comment]
@TheoLeCalvar oops, I'll look at this now!

@ValentinBesnard that is actually the intended behaviour - the event is saying that a certain element within the containment reference was deleted. Therefore, the container was affected by having a child object be deleted.

**Comment by agarciadom** [comment]
Fixed the relative paths issue. On second thought, you might be on to something @ValentinBesnard about the change events. I'll look at this again.

**Comment by ValentinBesnard** [comment]
See the pull request

**Comment by ValentinBesnard** [comment]
Maybe it can be useful to also add: ```change.setDeletedElement(<the element to remove>);```
to have both the ```affectedElement``` and the ```deletedElement```

**Comment by agarciadom** [comment]
Yep, I did that. I also fixed a silly mistake with single-valued containment refs.
