### ISSUE TITLE
Report metrics for custom phases

### ISSUE THREAD

**Issue by TheoLeCalvar** [TransformationToolContest/ttc2019-live#7]
In the case study description it is required to emit metric for three phases, `Init`, `Load` and `Run`.
However, is it possible to report custom phases ?

For instance, in the case the consistency checking is included in the transformation and thus the transformation have to be performed first it could be relevant to distinguish the transformation time from the time necessary to perform the check.

**Comment by agarciadom** [comment]
Sure, you can add custom phases if you like. Our visualisation tools might not pick those up, though - @georghinkel, can you provide details?

I would suggest perhaps reporting the three standard phases, and then adding further breakdowns into subphases (e.g. "Consistency" within "Run").

**Comment by georghinkel** [comment]
You can just omit your own phases as you like. Then, in the `config/reporting.json`, you need to define a new set of phases for which you want diagrams to be created. You can also specify multiple phases in there and rename them, this makes the R script to sum up all the provided phases for each run.

**Comment by TheoLeCalvar** [comment]
Ok, thanks for the explanation.
Right now we are reporting `Init`, `Load`, `LoadModels`, `Transform`, `PostProcess` and `Run` with `Load` = `LoadModels` + `Transform` + `PostProcess`.

I'll try to adapt the reporting configuration according to your advices.
